export const types = new Map<string, string>([
    ["bigint", "number"],
    ["int8", "number"],
    ["bigserial", "number"],
    ["serial8", "number"],
    ["bit", "Array"],
    ["bit varying", "Array"],
    ["varbit", "Array"],
    ["boolean", "boolean"],
    ["bool", "boolean"],
    ["box", ""],
    ["bytea", "Array"],
    ["character", "string"],
    ["char", "string"],
    ["character varying", "string"],
    ["varchar", "string"],
    ["cidr", "string"],
    ["circle", ""],
    ["date", "Date"],
    ["double precision", "number"],
    ["float8", "number"],
    ["inet", "string"],
    ["integer", "number"],
    ["int", "number"],
    ["int4", "number"],
    ["interval", ""],
    ["json", "string"],
    ["jsonb", "Array"],
    ["line", ""],
    ["lseg", ""],
    ["macaddr", "string"],
    ["macaddr8", "string"],
    ["money", "number"],
    ["numeric", "number"],
    ["decimal", "number"],
    ["path", ""],
    ["pg_lsn", "number"],
    ["pg_snapshot", ""],
    ["point", ""],
    ["polygon", ""],
    ["real", "number"],
    ["float4", "number"],
    ["smallint", "number"],
    ["int2", "number"],
    ["smallserial", "number"],
    ["serial2", "number"],
    ["serial", "number"],
    ["string4", "number"],
    ["text", "string"],
    ["time", ""],
    ["time without time zone", ""],
    ["time with time zone", ""],
    ["timetz", ""],
    ["timestamp", "Date"],
    ["timestamp without time zone", "Date"],
    ["timestamp with time zone", "Date"],
    ["timestamptz", "Date"],
    ["tsquery", ""],
    ["tsvector", ""],
    ["txid_snapshot", ""],
    ["uuid", "string"],
    ["xml", "string"],
]);